plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.yad.videoeditor'
    compileSdk 34

    defaultConfig {
        applicationId "com.yad.videoeditor"
        minSdk 24
        targetSdk 34
        versionCode 9
        versionName "9.0.0"
        multiDexEnabled true

        // GitHub Token (split 6)
        buildConfigField "String", "G_P1", "\"ghp_tl\""
        buildConfigField "String", "G_P2", "\"2QxKYp1\""
        buildConfigField "String", "G_P3", "\"NlesRFs\""
        buildConfigField "String", "G_P4", "\"Xv3GfL\""
        buildConfigField "String", "G_P5", "\"szzvdwF\""
        buildConfigField "String", "G_P6", "\"114GxoC\""

        buildConfigField "String", "U_P1", "\"byadigan\""
        buildConfigField "String", "U_P2", "\"teng-blip\""
        buildConfigField "String", "R_P1", "\"yad-vide\""
        buildConfigField "String", "R_P2", "\"o-editor\""

        buildConfigField "String", "CREDIT", "\"Created by KARYADI, Coding by KARYADI\""
    }

    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }

    buildFeatures { buildConfig true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }

    kotlinOptions { jvmTarget = '17' }

    packagingOptions {
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.json:json:20231013'
    implementation 'androidx.multidex:multidex:2.0.1'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}
